---
- hosts: localhost
  tasks:
  - name: Criar grupo de seguranca com HTTPS, HTTP e SSH
    ec2_group:
    name: digitalhouse
    vpc_id: vpc-087d809fb8ba93168
    description: sg com as regras
    region: us-west-1
      rules:
    - protocol: tcp
      ports:
      - 443
      - 80
      - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: Aceito todo o trafego nas portas 443, 80 e 22
- name: Criamos nosso servidor
  ec2:
    region: us-west-1
    group: digitalhouse
    instance_type: t2.micro
    image: ami-0ed05376b59b90e46
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: / dev / xvda
        volume_type: gp2
        volume_size: 8
    vpc_subnet_id: subnet-0796cf770e133d5a0
    assign_public_ip: sim
    key_name: pairKeyHelicoptero
  register: info
- name: IP publico do nosso servidor
  debug:
    var: info.instances[0].public_ip
- name: DNS publico de nosso servidor
  debug:
    var: info.instances[0].public_dns_name